'use client'
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import Sidebar from './components/Sidebar';
import Navbar from './components/Navbar';
import styled from 'styled-components';
import { AuthProvider } from "./context/AuthContext";

const Content = styled.div`
  margin-left: 10%;
  padding: 20px;
  @media (max-width: 768px) {
    margin-left: 0;
    margin-bottom: 60px;
  }
`;

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AuthProvider>
      <Navbar />
      <Sidebar />
      <content>
   
      {children}
    
      </content>
        
      </AuthProvider>
      </body>
    </html>
  );
}
